name: SoMCBasePlugin
version: 1.2
main: club.somc.base.BasePlugin
commands:
  setbase:
    description: Will set your current location to your base.
    usage: /<command>
    permission: somcbase.base
  base:
    description: Will return you to your base.
    usage: /<command>
    permission: somcbase.return
  baseflight:
    description: Will set baseflight to on or off.
    usage: /<command> (on|off)
    permission: somcbase.flight